import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { apiClient, apiServer } from '@/utils/apiClient'
import { useEffect } from 'react'
import axios from 'axios'
import Link from 'next/link'

// export async function getServerSideProps() {
//   let data = {
//     name: 'init',
//     gender: 'init',
//   }
//   await apiClient
//     .get('api/test')
//     .then((res) => {
//       data = {
//         name: res.data.name,
//         gender: res.data.gender,
//       }
//     })
//     .catch((err) => {
//       console.error(err)
//     })
//   return {
//     props: {
//       data,
//     },
//   }
// }

export default function Home(props: any) {
  // console.log('props', props)

  const fetcherGet = async (url: string) =>
    apiClient
      .get(url)
      .then((res) => {
        return res
      })
      .catch((err) => {
        console.log(err)
      })

  const fetcherPost = (url: string, body: Object = {}) =>
    apiClient
      .post(url, JSON.stringify(body))
      .then((res) => {
        return { data: res.data, err: undefined }
      })
      .catch((err) => {
        return { data: null, err: err.response }
      })

  const fetch = async () => {
    await fetcherGet('/sanctum/csrf-cookie')
    const { data, err } = await fetcherPost('/api/login', {
      email: 'user1@example.com',
      password: 'aaaa',
    })

    console.log(data, err)
  }

  useEffect(() => {
    // fetch()
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <Link className={styles.title} href='/login'>
          Welcome to Next.js!
        </Link>

        <p className={styles.description}>
          Get started by editing <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href='https://nextjs.org/docs' className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href='https://nextjs.org/learn' className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a href='https://github.com/vercel/next.js/tree/canary/examples' className={styles.card}>
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href='https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
            target='_blank'
            rel='noopener noreferrer'
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>Instantly deploy your Next.js site to a public URL with Vercel.</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
